### ISSUE TITLE
"Bad library name: lfs"

### ISSUE THREAD

**Issue by Frityet** [LuaLanes/lanes#226]
Code im running
```lua
local lanes = require("lanes").configure()
local lfs = lanes.require("lfs")

local function walk(dir, out)
    return lanes.gen("*,lfs", function()
        for file in lfs.dir(dir) do
            if file ~= "." and file ~= ".." then
                local path = dir .. "/" .. file
                if lfs.attributes(path, "mode") == "directory" then
                    walk(path, out)
                else
                    out:send(path)
                end
            end
        end
    end)()
end

local files = lanes.linda()
walk(".", files)

while true do
    local path = files:receive(1)
    if path then
        print(path)
    else
        break
    end
end

```

System information:
```yaml
❯ lua -v
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio

❯ uname -a
Darwin amrit-1642.local 22.6.0 Darwin Kernel Version 22.6.0: Mon Feb 19 19:48:53 PST 2024; root:xnu-8796.141.3.704.6~1/RELEASE_X86_64 x86_64

❯ sw_vers
ProductName:            macOS
ProductVersion:         13.6.6
BuildVersion:           22G630
```

without the `",lfs"` in the `lanes.gen` call, i get 
```yaml
lua: /usr/local/share/lua/5.4/lanes.lua:336: main: function 'lfs/<SOME LFS SYMBOL, CHANGES EVERY RUN>' not found in Lane #0x7fcce800aa08 destination transfer database.
```
